# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
     stdlib: "puppetlabs/stdlib"
     supervisor: "proletaryo/supervisor"
     vcsrepo: "puppetlabs/vcsrepo"
     python: "puppet/python"
     git: "puppetlabs/git"
     epel: "stahnma/epel"
     yumrepo_core: "puppetlabs/yumrepo_core"
     firewalld: "crayfishx/firewalld"